<?php
// based on https://github.com/KnpLabs/php-github-api
// Docs: https://github.com/KnpLabs/php-github-api/tree/master/doc

// This file is generated by Composer
require_once 'vendor/autoload.php';

// initialize the sdk
$client = new Github\Client();

// additional variables
$plugin_slug = ''; // e.g. 'wp-piwik'
$plugin_name = ''; // e.g. 'WP-Piwik'
$plugin_svn = ''; // e.g. 'http://plugins.svn.wordpress.org/wp-piwik/'
$plugin_desc = 'WordPress-Mirror: ' . $plugin_name . 'SVN repository (' . $plugin_svn . ')';
$plugin_url = '';

// Requires authentication: https://github.com/KnpLabs/php-github-api/blob/master/doc/security.md
$repo = $client->api('repo')->create( $plugin_slug, $plugin_desc, $plugin_url, true);
?>
